<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>    
    <PackageVersion Include="System.Reactive" Version="6.0.1" />
    <PackageVersion Include="Microsoft.Reactive.Testing" Version="6.0.1" />
    <PackageVersion Include="MaterialColorUtilities" Version="0.3.0" />
    <PackageVersion Include="MaterialColorUtilities.Maui" Version="0.3.0" />
    <PackageVersion Include="Plugin.Maui.Audio" Version="3.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.14" />    
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.7.250401001" />
    <PackageVersion Include="Appium.WebDriver" Version="7.2.0" />    
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.0-preview.3.25208.1" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.0-preview.3.25208.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0-preview.3.25171.5" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.0-preview.3.25171.5" />
  </ItemGroup>
</Project>