<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>UITests</RootNamespace>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Appium.WebDriver" />
    <PackageReference Include="Microsoft.Reactive.Testing" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\UITests.Shared\**\*.cs" LinkBase="Shared" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Verifable.General\Verifable.General.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage">
      <VersionOverride>18.5.2</VersionOverride>
    </PackageReference>
  </ItemGroup>

</Project>