name: Deploy Veriable Main Web Site
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: "web"

      - name: Build & Deploy Worker        
        if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'Lumoin' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "web"
          command: deploy --site public/
