name: Verifable build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ~/.nuget/packages
  BUILD_CONFIGURATION: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: android
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: ios
          - os: macos-latest
            platform: maccatalyst

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: 2

      - name: Cache Nuget packages '${{ matrix.platform }}'
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup .NET SDK using global.json
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Restore local tools
        run: dotnet tool restore

      - name: Add Problem Matcher for dotnet-format
        uses: xt0rted/dotnet-format-problem-matcher@b90c4f18e3daa4f8fd266e41eba4f351b2e00b75

      # Optional: Uncomment to run dotnet format check
      # - name: Run dotnet format
      #   run: dotnet format --check

      - name: Create directory for SBOM
        run: mkdir -p "${{ github.workspace }}/${{ matrix.platform }}/sbom/"

      - name: Run BOM analysis
        run: dotnet tool run sbom-tool generate -DeleteManifestDirIfPresent true -BuildDropPath "${{ github.workspace }}/${{ matrix.platform }}/sbom/" -FetchLicenseInformation true -EnablePackageMetadataParsing true -BuildComponentPath . -PackageName "Verifiable" -PackageSupplier "Lumoin" -NamespaceUriBase "https://lumoin.com/verifiable" -PackageVersion 1.0.0 -Verbosity Verbose

      - name: Build
        run: |
          dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }} /p:ContinuousIntegrationBuild=true
          dotnet publish --no-restore -c ${{ env.BUILD_CONFIGURATION }} -o ./publish/${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-artifact
          path: ./publish/${{ matrix.platform }}
